### ISSUE TITLE
Getting a warning: The batch will be filled until we reach 1,its size may exceed 32 tokens

### ISSUE THREAD

**Issue by ottokruse** [schwallergroup/ai4chem_course#10]
When I run through notebook 7 "Reaction prediction" upon training the model I see these warnings appear:

`[2024-02-14 12:29:19,397 WARNING] The batch will be filled until we reach 1,its size may exceed 32 tokens`

Any guidance on what to do? Related: in the hyperparams I see you use batch_size: 6144, which is a bit of an odd number and looks like you may have tuned it to get rid of the warning?

Thank you

This warning is also addressed on the ONMT forum ([link](https://forum.opennmt.net/t/the-batch-will-be-filled-until-we-reach-1-its-size-may-exceed-16-tokens/4059)) and they suggest to set `batch_type` to `sents`, but I believe this is for version 3 upwards and the notebooks explicitly installs `OpenNMT-py==2.2.0`. Had a quick test with version 3 but that quickly led me to other issues so I'll stick with 2.2.0 for now.

**Comment by ottokruse** [comment]
Looks like we may need to specify `valid_batch_size` because the default is 32.

Assume it must have some relation to `batch_size` but in the examples I see it's certainly not 1:1

Default batch_size is 64 and default valid_batch_size is 32: https://opennmt.net/OpenNMT-py/options/train.html

**Comment by pschwllr** [comment]
Hi Otto, 

```
 "--batch_type",
  "-batch_type",
  default="sents",
  choices=["sents", "tokens"],
  help="Batch grouping for batch_size. Standard "
  "is sents. Tokens will do dynamic batching"
```

I think that `dynamic batching` makes sense, and that you can safely ignore the warning. 

Dynamic batching groups inputs by the number of tokens, allowing each batch to contain varying sentence lengths. This can make better use of GPU/TPU memory compared to padding all sentences to a fixed length.

Empirically, the results of the Molecular Transformer are pretty robust to the batch_size (if large enough). 
With dynamic batching, batch size is measured in tokens that's why there is such a large number. Aim to maximize batch size without running out of memory.

**Comment by ottokruse** [comment]
Thanks @pschwllr 👍
